version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: p8_mongo_step3
    environment:
      MONGO_INITDB_DATABASE: meteo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:1.0.2
    container_name: p8_mongo_express_step3
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - mongo

  migrate:
    build:
      context: .
    container_name: p8_migrate_step3
    environment:
      MONGO_URI: "mongodb://mongo:27017"
      MONGO_DB: "meteo"
      IN_DIR: "/data/in"
      OUT_DIR: "/data/out"
    volumes:
      - ../output/01_local_processing:/data/in:ro
      - ../output/02_local_processing:/data/out
    depends_on:
      - mongo
    command: ["python", "-u", "main.py"]

volumes:
  mongo_data:
